import { isIP } from 'node:net';
import { FieldValue } from 'firebase-admin/firestore';
import { adminDb } from '../firebaseAdmin.js';
import { CloudflareDnsRecordInput } from './CloudflareDnsService.js';
export const DNS_TYPES=new Set(['A','AAAA','CNAME','MX','TXT','CAA','SRV']); export const PROXY_TYPES=new Set(['A','AAAA','CNAME']); const s=(v:unknown)=>String(v??'').trim();
export function normalizeRecordName(v:unknown,domain:string){const x=s(v).toLowerCase().replace(/\.$/,'');if(!x||x==='@')return domain;if(x===domain||x.endsWith('.'+domain))return x;if(!/^[a-z0-9_*.-]+$/i.test(x))throw new Error('Enter a valid DNS record name.');return `${x}.${domain}`}
function hostname(v:unknown,label:string){const x=s(v).toLowerCase().replace(/\.$/,'');if(!x||x.length>253||!/^[a-z0-9._-]+$/i.test(x))throw new Error(`${label} must be a valid hostname.`);return x}
function integer(v:unknown,label:string,min=0,max=65535){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`${label} must be between ${min} and ${max}.`);return n}
export function dnsInput(body:any,domain:string):CloudflareDnsRecordInput{const type=s(body?.type).toUpperCase();if(!DNS_TYPES.has(type))throw new Error('Supported record types are A, AAAA, CNAME, MX, TXT, CAA and SRV.');const raw=Number(body?.ttl??1);const ttl=raw===1?1:Math.max(60,Math.min(86400,Math.floor(raw||1)));const name=normalizeRecordName(body?.name,domain);const value=s(body?.value??body?.content);
if(type==='A'&&isIP(value)!==4)throw new Error('Value must be a valid IPv4 address.');if(type==='AAAA'&&isIP(value)!==6)throw new Error('Value must be a valid IPv6 address.');if(type==='CNAME'){const t=hostname(value,'CNAME value');if(t===name)throw new Error('A CNAME cannot point to itself.')}if(type==='MX')hostname(value,'MX value');if((type==='TXT'||type==='CAA')&&!value)throw new Error(`${type} value is required.`);
if(type==='SRV'){const target=hostname(body?.target??value,'SRV target');const priority=integer(body?.priority,'SRV priority'),weight=integer(body?.weight,'SRV weight'),port=integer(body?.port,'SRV port');return {type:'SRV',name,content:`${weight} ${port} ${target}`,ttl,proxied:false,data:{priority,weight,port,target}} as any}
if(!value)throw new Error('Record value is required.');const o:any={type,name,content:value,ttl,proxied:PROXY_TYPES.has(type)?Boolean(body?.proxied):false};if(type==='MX'){o.priority=integer(body?.priority,'MX priority');o.proxied=false}return o}
export async function dnsAudit(a:{domainId:string;domainName:string;actorUid:string;actorEmail?:string;actorRole:'customer'|'admin';action:'create'|'update'|'delete';recordId?:string;record?:any}){await adminDb.collection('dns_activity').add({...a,created_at:FieldValue.serverTimestamp()})}
