import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2 } from 'lucide-react';

type Guide = { title:string; intro:string; steps:{title:string; body:string}[]; note?:string };

const data: Record<string, Guide> = {
  'connect-domain-to-vercel': { title:'How to connect a domain to Vercel', intro:'Connect a Runtime-managed domain to a Vercel project by adding the domain in Vercel first, then creating the DNS records Vercel gives you.', steps:[{title:'Add the domain in Vercel',body:'Open the project in Vercel, add your custom domain, and note the DNS configuration Vercel requests.'},{title:'Open DNS management',body:'If the domain uses Runtime DNS, open its Runtime DNS manager. If it uses Custom DNS, make the change with the DNS provider that hosts its authoritative nameservers.'},{title:'Create the requested records',body:'Add the exact A, CNAME or other records Vercel provides. Do not guess record values, because Vercel may give different instructions depending on the domain and project.'},{title:'Verify in Vercel',body:'Return to Vercel and verify the domain after DNS has propagated.'}] },
  'connect-domain-to-netlify': { title:'How to connect a domain to Netlify', intro:'Add the domain to your Netlify site, then publish the DNS records Netlify specifies at the authoritative DNS provider.', steps:[{title:'Add the custom domain',body:'In Netlify, add the domain to the site you want it to serve.'},{title:'Copy Netlify’s DNS instructions',body:'Use the record names, types and values shown for your site.'},{title:'Add records in Runtime DNS or your provider',body:'For Runtime DNS, add the records in the domain DNS manager. For Custom DNS, update them with your existing DNS provider.'},{title:'Check verification',body:'Allow time for DNS changes to propagate, then confirm the domain status in Netlify.'}] },
  'connect-domain-to-render': { title:'How to connect a domain to Render', intro:'Render custom domains are connected by adding the domain to your Render service and then publishing the DNS records Render requests.', steps:[{title:'Add your custom domain in Render',body:'Open the relevant Render service and add the domain.'},{title:'Read the required DNS records',body:'Render will show the record target needed for the service.'},{title:'Publish the records',body:'Create those records in Runtime DNS, or at your current provider when the domain uses Custom DNS.'},{title:'Wait for verification',body:'DNS propagation is not instant. Keep the records in place and check Render for verification and certificate status.'}] },
  'connect-domain-to-github-pages': { title:'How to connect a domain to GitHub Pages', intro:'Use GitHub Pages custom-domain settings together with DNS records at the domain’s authoritative DNS provider.', steps:[{title:'Set the custom domain in GitHub',body:'Open the repository Pages settings and enter the domain you want to use.'},{title:'Use GitHub’s current DNS values',body:'Follow the DNS values shown in GitHub’s documentation or Pages settings for the apex domain or subdomain you are connecting.'},{title:'Add the records',body:'Publish the records in Runtime DNS if Runtime manages the zone. Otherwise update your Custom DNS provider.'},{title:'Enable HTTPS when available',body:'After GitHub verifies the DNS, enable HTTPS when the option becomes available.'}] },
  'connect-domain-to-firebase': { title:'How to connect a domain to Firebase Hosting', intro:'Firebase Hosting verifies domain ownership and provides DNS records that must be published before the custom domain becomes active.', steps:[{title:'Add the domain in Firebase Hosting',body:'Choose the Hosting site and start the custom-domain setup.'},{title:'Complete ownership verification',body:'Firebase may request a TXT record. Add the exact verification record it provides.'},{title:'Add serving records',body:'After verification, add the A, AAAA, CNAME or other records Firebase specifies for the domain.'},{title:'Keep records until provisioning completes',body:'Certificate and DNS provisioning can take time. Check Firebase Hosting for the final status.'}] },
  'connect-domain-to-vps-hosting': { title:'How to connect a domain to a VPS or hosting server', intro:'A domain can point directly to a server or use the nameservers supplied by a hosting provider. The correct option depends on how your hosting is configured.', steps:[{title:'Get the hosting details',body:'Ask your host for the server IP address and any required DNS records, or for the authoritative nameservers if they manage DNS for you.'},{title:'Choose DNS management',body:'To keep Runtime DNS, create the required A, AAAA, CNAME, MX and other records in Runtime. To let the host manage DNS, change the domain to the host’s nameservers as Custom DNS.'},{title:'Point the web records',body:'An A record commonly points a hostname to an IPv4 address; an AAAA record points to IPv6. Use only the values supplied for your server.'},{title:'Configure the server too',body:'DNS only directs traffic. Your web server or hosting panel must also be configured to accept the domain and provide HTTPS.'}] },
  'dns-records': { title:'DNS records explained: A, AAAA, CNAME, MX, TXT and more', intro:'DNS records tell resolvers where services for a domain live. These are the record types you will most often see when connecting a domain.', steps:[{title:'A and AAAA',body:'A points a hostname to an IPv4 address. AAAA does the same for an IPv6 address.'},{title:'CNAME',body:'CNAME aliases one hostname to another hostname. Providers often use it for subdomains such as www.'},{title:'MX',body:'MX records identify mail servers for a domain. Priority values matter when more than one MX record exists.'},{title:'TXT',body:'TXT records carry text used for ownership verification and email authentication mechanisms such as SPF.'},{title:'NS',body:'NS records identify authoritative nameservers. For Runtime DNS, Cloudflare assigns the nameservers for each individual zone.'}] },
  'register-co-zw-domain': { title:'How to register a .co.zw domain with Runtime', intro:'Search for the name, complete the Runtime order and registrant details, then wait for the registry workflow to complete.', steps:[{title:'Search the domain',body:'Use Runtime’s domain search to check whether the .co.zw name is available.'},{title:'Start registration',body:'Choose the available domain and complete the required account and registrant information.'},{title:'Complete payment',body:'Follow the checkout flow for the order. Runtime only treats a provider-confirmed payment as settled.'},{title:'Registry processing',body:'The .co.zw registration is processed through the applicable ZISPA/registry workflow. Availability checks do not override registry rules or final processing.'},{title:'Choose DNS',body:'After registration, use Runtime DNS powered by Cloudflare or configure Custom DNS nameservers for another provider.'}] },
};

export const GuidePage: React.FC = () => {
  const { slug = '' } = useParams();
  const guide = data[slug];
  if (!guide) return null;
  return <article className="bg-white"><div className="mx-auto max-w-3xl px-4 py-14 sm:px-6 lg:px-8"><Link to="/guides" className="inline-flex items-center gap-2 text-sm font-semibold text-[#3120ff]"><ArrowLeft className="h-4 w-4" />All guides</Link><h1 className="mt-6 text-4xl font-bold tracking-tight text-zinc-950 sm:text-5xl">{guide.title}</h1><p className="mt-5 text-lg leading-8 text-zinc-600">{guide.intro}</p><div className="mt-10 space-y-8">{guide.steps.map((step,i)=><section key={step.title} className="border-t border-zinc-200 pt-7"><div className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#3120ff]/10 text-sm font-bold text-[#3120ff]">{i+1}</span><div><h2 className="text-xl font-bold text-zinc-950">{step.title}</h2><p className="mt-2 text-sm leading-7 text-zinc-600">{step.body}</p></div></div></section>)}</div><aside className="mt-10 rounded-2xl border border-zinc-200 bg-[#FAFAFA] p-6"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-[#3120ff]"/><p className="text-sm leading-7 text-zinc-600">Always use the DNS values shown by the service you are connecting. Platform instructions can change, and DNS changes may take time to propagate.</p></div></aside></div></article>;
};
