import React,{useEffect,useMemo,useState} from 'react';
import { getAuth } from 'firebase/auth';
import { ArrowRight, CheckCircle2, Loader2, RefreshCw, ShieldCheck, X } from 'lucide-react';

const API=import.meta.env.VITE_API_BASE_URL||(import.meta.env.DEV?'http://localhost:4000':'https://api.runtime.co.zw');
const key=(r:any)=>[String(r.type||'').toUpperCase(),String(r.name||'').toLowerCase(),String(r.content||''),String(r.priority??'')].join('|');

export const RuntimeDnsMigration:React.FC<{domain:any;onClose:()=>void;actor?:'customer'|'admin'}>=({domain,onClose,actor='customer'})=>{
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Set<string>>(new Set());
 const request=async(path:string,init:any={})=>{const u=getAuth().currentUser;if(!u)throw new Error('Authentication required.');const token=await u.getIdToken();const r=await fetch(`${API}/api/dns-migration/${domain.id}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init.headers}});const b=await r.json().catch(()=>({}));if(!r.ok||b.success===false)throw new Error(b.message||'Request failed.');return b};
 const load=async()=>{try{setBusy(true);setError('');const b=await request('');setData(b);const all=new Set<string>((b.records||[]).map(key));setSelected(all)}catch(e){setError(e instanceof Error?e.message:'Unable to load migration.')}finally{setBusy(false)}};
 useEffect(()=>{load()},[domain.id]);
 const start=async()=>{try{setBusy(true);setError('');await request('/start',{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to start migration.');setBusy(false)}};
 const refresh=async()=>{try{setBusy(true);setError('');const b=await request('/refresh',{method:'POST'});setData((d:any)=>({...d,records:b.records,migration:{...d?.migration,status:'review_required'}}));setSelected(new Set((b.records||[]).map(key)))}catch(e){setError(e instanceof Error?e.message:'Unable to refresh scan.')}finally{setBusy(false)}};
 const review=async()=>{try{setBusy(true);setError('');const b=await request('/review',{method:'POST',body:JSON.stringify({selectedKeys:[...selected]})});setData((d:any)=>({...d,migration:{...d.migration,status:b.status,pendingNameservers:b.pendingNameservers}}))}catch(e){setError(e instanceof Error?e.message:'Unable to import records.')}finally{setBusy(false)}};
 const registrarSubmitted=async()=>{if(!window.confirm('Confirm only after you have submitted these exact Runtime DNS nameservers to the registrar/ZISPA. Continue?'))return;try{setBusy(true);setError('');const b=await request('/registry-submitted',{method:'POST'});setData((d:any)=>({...d,migration:{...d.migration,status:b.status,pendingNameservers:b.nameservers}}))}catch(e){setError(e instanceof Error?e.message:'Unable to record registrar submission.')}finally{setBusy(false)}};
 const records=data?.records||[]; const status=data?.migration?.status; const ready=status==='ready_for_registry'; const delegationPending=status==='delegation_pending'; const completed=status==='completed';
 return <div className="fixed inset-0 z-70 bg-black/40 p-4"><div className="mx-auto flex max-h-[94vh] max-w-4xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl">
  <div className="flex items-center justify-between border-b border-zinc-200 px-5 py-4"><div><p className="text-xs font-bold text-[#3120ff]">{actor==='admin'?'DNS migration · Administrator':'Move to Runtime DNS'}</p><h2 className="mt-1 font-mono text-base font-bold">{domain.domain_name}</h2></div><button onClick={onClose} className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-100"><X className="h-5 w-5"/></button></div>
  <div className="overflow-y-auto p-5">
   <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-700"/><div><p className="text-xs font-bold text-emerald-950">Your current DNS stays online</p><p className="mt-1 text-[11px] leading-5 text-emerald-800">Runtime will not change your current nameservers during this preparation stage. First we scan and copy your DNS records for review.</p></div></div></div>
   {data&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-3"><p className="text-[10px] uppercase text-zinc-400">Current nameservers</p>{(data.currentNameservers||[]).map((n:string)=><p key={n} className="mt-1 break-all font-mono text-xs">{n}</p>)}</div><div className="rounded-xl border p-3"><p className="text-[10px] uppercase text-zinc-400">Runtime DNS nameservers</p>{(data.migration?.pendingNameservers||[]).length?(data.migration.pendingNameservers.map((n:string)=><p key={n} className="mt-1 break-all font-mono text-xs">{n}</p>)):<p className="mt-1 text-xs text-zinc-500">Created after you start migration.</p>}</div></div>}
   {!status&&<div className="mt-5"><p className="text-sm font-bold">Step 1 · Prepare Runtime DNS</p><p className="mt-1 text-xs text-zinc-500">Cloudflare will scan common DNS records while your existing nameservers remain authoritative.</p><button disabled={busy} onClick={start} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#3120ff] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ArrowRight className="h-4 w-4"/>}Start migration</button></div>}
   {status&&!ready&&!delegationPending&&!completed&&<div className="mt-5"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">Step 2 · Review discovered records</p><p className="mt-1 text-xs text-zinc-500">Keep every record your website, email and verification services need.</p></div><button disabled={busy} onClick={refresh} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>Refresh scan</button></div>
    {records.length?<div className="mt-3 overflow-x-auto rounded-xl border"><table className="w-full text-left text-xs"><thead className="bg-zinc-50 text-[10px] uppercase text-zinc-500"><tr><th className="p-3">Keep</th><th className="p-3">Type</th><th className="p-3">Name</th><th className="p-3">Value</th><th className="p-3">TTL</th></tr></thead><tbody className="divide-y">{records.map((r:any)=>{const k=key(r);return <tr key={k}><td className="p-3"><input type="checkbox" checked={selected.has(k)} onChange={e=>setSelected(v=>{const n=new Set(v);e.target.checked?n.add(k):n.delete(k);return n})}/></td><td className="p-3 font-bold">{r.type}</td><td className="p-3 font-mono">{r.name}</td><td className="max-w-[320px] break-all p-3 font-mono">{r.content}</td><td className="p-3">{r.ttl===1?'Auto':r.ttl}</td></tr>})}</tbody></table></div>:<div className="mt-3 rounded-xl border border-dashed p-5 text-center text-xs text-zinc-500">The scan has not found supported records yet. Wait a little, then refresh. Do not continue until the DNS records you need are present.</div>}
    <button disabled={busy||selected.size===0} onClick={review} className="mt-3 rounded-xl bg-zinc-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">Import {selected.size} selected record{selected.size===1?'':'s'}</button>
   </div>}
   {ready&&<div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4"><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-blue-700"/><div className="w-full"><p className="text-sm font-bold text-blue-950">DNS preparation complete</p><p className="mt-1 text-xs leading-5 text-blue-800">The selected records are prepared in Runtime DNS. The original nameservers are still authoritative.</p>{actor==='admin'?<><p className="mt-3 text-[11px] font-bold text-blue-950">Submit these exact nameservers to the registrar/ZISPA first:</p>{(data?.migration?.pendingNameservers||[]).map((n:string)=><p key={n} className="mt-1 font-mono text-xs text-blue-950">{n}</p>)}<button disabled={busy} onClick={registrarSubmitted} className="mt-3 rounded-xl bg-blue-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">I have submitted the nameserver change</button></>:<p className="mt-2 text-[11px] font-semibold text-blue-900">Runtime support must now submit the nameserver change to the registrar. No action is required from you yet.</p>}</div></div></div>}{delegationPending&&<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-bold text-amber-950">Nameserver change pending</p><p className="mt-1 text-xs leading-5 text-amber-800">The registrar change has been submitted. Runtime DNS stays Pending until the registry publishes the new delegation and Cloudflare confirms the zone as Active.</p></div>}{completed&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-sm font-bold text-emerald-950">Runtime DNS is active</p><p className="mt-1 text-xs leading-5 text-emerald-800">The new nameserver delegation has been detected. Close this window and use Manage DNS.</p></div>}
   {error&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}
  </div>
 </div></div>
}
