import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowUp, Clock3, Copy, Gauge, Globe2, MapPin, Network, RefreshCw, ShieldCheck, ThumbsUp, Wifi } from 'lucide-react';
import { FaFacebookF, FaLinkedinIn, FaWhatsapp, FaXTwitter } from 'react-icons/fa6';

type Phase='idle'|'ping'|'download'|'upload'|'done'|'error';
type Results={ping:number|null;jitter:number|null;download:number|null;upload:number|null;loadedPing:number|null;packetLoss:number|null};
type Meta={clientIp?:string;city?:string;region?:string;country?:string;colo?:string;asn?:number;asOrganization?:string};
const initial:Results={ping:null,jitter:null,download:null,upload:null,loadedPing:null,packetLoss:null};
const DOWN='https://speed.cloudflare.com/__down';
const UP='https://speed.cloudflare.com/__up';
const META='https://speed.cloudflare.com/meta';
const API=import.meta.env.VITE_API_BASE_URL || (import.meta.env.DEV?'http://localhost:4000':'https://api.runtime.co.zw');
const median=(a:number[])=>{const s=[...a].sort((x,y)=>x-y);return s.length?s[Math.floor(s.length/2)]:0};
const fmt=(v:number|null,d=1)=>v==null?'—':v.toFixed(d);
const safeJson=async(res:Response)=>{try{return await res.json()}catch{return {}}};

export const SpeedTest:React.FC=()=>{
 const [phase,setPhase]=useState<Phase>('idle'); const [r,setR]=useState<Results>(initial); const [progress,setProgress]=useState(0); const [error,setError]=useState(''); const [meta,setMeta]=useState<Meta>({}); const [testedAt,setTestedAt]=useState<Date|null>(null); const [live,setLive]=useState(0); const [useful,setUseful]=useState(()=>localStorage.getItem('runtime-speedtest-useful')==='1'); const [usefulCount,setUsefulCount]=useState(0); const [copied,setCopied]=useState(false); const runId=useRef(0);
 useEffect(()=>{fetch(META,{cache:'no-store'}).then(async x=>{if(x.ok)setMeta(await safeJson(x))}).catch(()=>{});fetch(`${API}/api/speed-test/stats`,{cache:'no-store'}).then(x=>x.ok?x.json():null).then(x=>{if(x?.success)setUsefulCount(Number(x.useful_count||0))}).catch(()=>{});return()=>{runId.current++}},[]);
 const displayValue=phase==='download'||phase==='upload'?live:phase==='ping'?r.ping??live:phase==='done'?r.download??0:0;
 const displayUnit=phase==='ping'?'ms':'Mbps';
 const gaugeMax=phase==='ping'?150:Math.max(100,Math.ceil((Math.max(displayValue,r.download||0,r.upload||0)+20)/50)*50);
 const gaugePct=Math.min(1,displayValue/gaugeMax);
 const circumference=2*Math.PI*82;
 const quality=useMemo(()=>{if(phase!=='done'||r.download==null||r.ping==null)return null;if(r.download>=50&&r.ping<50)return['Excellent','Great for streaming, video calls and everyday use.'];if(r.download>=20&&r.ping<100)return['Good','Suitable for HD streaming, calls and general browsing.'];if(r.download>=5)return['Fair','Fine for browsing; heavy streaming or calls may vary.'];return['Limited','Basic browsing should work, but demanding tasks may struggle.']},[phase,r]);
 const measureLatency=async(id:number,count=6)=>{const vals:number[]=[];let failed=0;for(let i=0;i<count;i++){const t=performance.now();try{const res=await fetch(`${DOWN}?bytes=0&t=${Date.now()}-${i}`,{cache:'no-store'});if(!res.ok)throw 0;await res.arrayBuffer();vals.push(performance.now()-t)}catch{failed++}if(id!==runId.current)return {vals:[],failed};await new Promise(x=>setTimeout(x,70))}return{vals,failed}};
 const run=async()=>{const id=++runId.current;setR(initial);setError('');setTestedAt(null);setLive(0);setProgress(2);setPhase('ping');
  try{
   fetch(META,{cache:'no-store'}).then(async x=>{if(x.ok&&id===runId.current)setMeta(await safeJson(x))}).catch(()=>{});
   const base=await measureLatency(id,8);if(id!==runId.current)return;if(!base.vals.length)throw new Error('The test server did not respond.');const ping=median(base.vals);const diffs=base.vals.slice(1).map((v,i)=>Math.abs(v-base.vals[i]));const jitter=diffs.reduce((a,b)=>a+b,0)/Math.max(1,diffs.length);setR(x=>({...x,ping,jitter}));setLive(ping);setProgress(25);
   setPhase('download');const downPoints:number[]=[];for(const [i,size] of [1_000_000,5_000_000,10_000_000,15_000_000].entries()){const t=performance.now();const res=await fetch(`${DOWN}?bytes=${size}&t=${Date.now()}-${i}`,{cache:'no-store'});if(!res.ok)throw new Error('Download test failed.');const b=await res.arrayBuffer();const sec=(performance.now()-t)/1000;const speed=(b.byteLength*8/sec)/1e6;if(sec>0)downPoints.push(speed);if(id!==runId.current)return;const v=median(downPoints);setLive(v);setR(x=>({...x,download:v}));setProgress(32+i*8)}
   const loaded=await measureLatency(id,4);if(id!==runId.current)return;setR(x=>({...x,loadedPing:loaded.vals.length?median(loaded.vals):null,packetLoss:((base.failed+loaded.failed)/(12))*100}));
   setPhase('upload');setLive(0);const upPoints:number[]=[];for(const [i,size] of [500_000,1_000_000,2_000_000,4_000_000].entries()){const body=new Uint8Array(size);const t=performance.now();const res=await fetch(`${UP}?t=${Date.now()}-${i}`,{method:'POST',body,cache:'no-store'});if(!res.ok)throw new Error('Upload test failed.');await res.text();const sec=(performance.now()-t)/1000;const speed=(size*8/sec)/1e6;if(sec>0)upPoints.push(speed);if(id!==runId.current)return;const v=median(upPoints);setLive(v);setR(x=>({...x,upload:v}));setProgress(72+i*7)}
   setProgress(100);setPhase('done');setTestedAt(new Date());
  }catch(e:any){if(id!==runId.current)return;setError(e?.message||'The speed test could not be completed. Please try again.');setPhase('error');setProgress(0)}
 };
 const shareUrl=typeof window!=='undefined'?window.location.href:'https://runtime.co.zw/speed-test';
 const shareText=phase==='done'&&r.download!=null&&r.upload!=null?`My internet speed: ${fmt(r.download)} Mbps download and ${fmt(r.upload)} Mbps upload — tested with Runtime.`:'Test your internet speed with Runtime.';
 const share=(kind:string)=>{const u=encodeURIComponent(shareUrl),t=encodeURIComponent(shareText);const links:Record<string,string>={whatsapp:`https://wa.me/?text=${t}%20${u}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${u}`,x:`https://twitter.com/intent/tweet?text=${t}&url=${u}`,linkedin:`https://www.linkedin.com/sharing/share-offsite/?url=${u}`};if(links[kind])window.open(links[kind],'_blank','noopener,noreferrer');};
 const copyLink=async()=>{try{await navigator.clipboard.writeText(shareUrl);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
 const markUseful=async()=>{if(useful)return;try{const res=await fetch(`${API}/api/speed-test/useful`,{method:'POST',headers:{'Content-Type':'application/json'}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'Could not save feedback.');setUseful(true);setUsefulCount(Number(data.useful_count||0));localStorage.setItem('runtime-speedtest-useful','1')}catch{}};
 const active=!['idle','done','error'].includes(phase);const status=phase==='ping'?'Checking latency':phase==='download'?'Measuring download':phase==='upload'?'Measuring upload':phase==='done'?'Test complete':phase==='error'?'Test interrupted':'Ready to test';
 return <div className="bg-white">
  <section className="border-b border-zinc-100"><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16">
   <div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#3120ff]">Runtime Tools</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-zinc-950 sm:text-5xl">Internet Speed Test</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-zinc-600">Test your connection speed, responsiveness and network quality.</p></div>
   <div className="mx-auto mt-9 max-w-5xl overflow-hidden rounded-[28px] border border-zinc-200 bg-[#fafafa]">
    <div className="grid lg:grid-cols-[1.08fr_.92fr]">
     <div className="relative flex min-h-107.5 flex-col items-center justify-center border-b border-zinc-200 p-6 lg:border-b-0 lg:border-r sm:p-9">
      <div className="absolute left-6 top-6 flex items-center gap-2 text-xs font-semibold text-zinc-500"><span className={`h-2 w-2 rounded-full ${active?'animate-pulse bg-[#3120ff]':phase==='done'?'bg-emerald-500':'bg-zinc-300'}`}/>{status}</div>
      <div className="relative mt-7 h-64 w-64 sm:h-72 sm:w-72">
       <svg viewBox="0 0 200 200" className="h-full w-full -rotate-90" aria-hidden="true"><circle cx="100" cy="100" r="82" fill="none" stroke="#e4e4e7" strokeWidth="8" strokeLinecap="round" strokeDasharray={`${circumference*.78} ${circumference*.22}`}/><circle cx="100" cy="100" r="82" fill="none" stroke="#3120ff" strokeWidth="8" strokeLinecap="round" strokeDasharray={`${circumference*.78*gaugePct} ${circumference}`} className="transition-all duration-500 ease-out"/></svg>
       <div className="absolute inset-0 flex flex-col items-center justify-center text-center"><span className="text-[11px] font-bold uppercase tracking-[.16em] text-zinc-400">{phase==='download'?'Download':phase==='upload'?'Upload':phase==='ping'?'Ping':phase==='done'?'Download':'Runtime'}</span><div className="mt-1 text-5xl font-bold tabular-nums tracking-tight text-zinc-950 sm:text-6xl">{phase==='idle'?'GO':phase==='error'?'—':fmt(displayValue,phase==='ping'?0:1)}</div>{phase!=='idle'&&<span className="mt-1 text-sm font-medium text-zinc-500">{displayUnit}</span>}</div>
      </div>
      <button type="button" disabled={active} onClick={run} className="mt-1 inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[#3120ff] px-7 text-sm font-bold text-white transition hover:scale-[1.02] disabled:cursor-wait disabled:opacity-70">{phase==='idle'?<><Wifi className="h-4 w-4"/>Start test</>:<><RefreshCw className={`h-4 w-4 ${active?'animate-spin':''}`}/>{active?`${Math.round(progress)}%`:'Test again'}</>}</button>
      <p className="mt-3 min-h-5 text-center text-xs text-zinc-500" aria-live="polite">{phase==='error'?error:active?'Keep this tab open while Runtime tests your connection.':phase==='done'?'Results can vary with Wi-Fi, congestion and routing.':'Ready when you are.'}</p>
     </div>
     <div className="p-6 sm:p-9"><p className="text-xs font-bold uppercase tracking-[.15em] text-zinc-400">Connection results</p><div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-6"><Result icon={<ArrowDown/>} name="Download" value={fmt(r.download)} unit="Mbps"/><Result icon={<ArrowUp/>} name="Upload" value={fmt(r.upload)} unit="Mbps"/><Result icon={<Activity/>} name="Ping" value={fmt(r.ping,0)} unit="ms"/><Result icon={<Gauge/>} name="Jitter" value={fmt(r.jitter,0)} unit="ms"/><Result icon={<Activity/>} name="Loaded latency" value={fmt(r.loadedPing,0)} unit="ms"/><Result icon={<ShieldCheck/>} name="Packet loss" value={fmt(r.packetLoss,1)} unit="%"/></div>
      {quality&&<div className="mt-7 rounded-2xl border border-zinc-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-bold text-zinc-950">Connection quality</span><span className="rounded-full bg-[#3120ff]/10 px-3 py-1 text-xs font-bold text-[#3120ff]">{quality[0]}</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{quality[1]}</p></div>}
     </div>
    </div>
    <div className="border-t border-zinc-200 bg-white px-6 py-5 sm:px-9"><div className="grid gap-5 sm:grid-cols-3"><Detail icon={<Network/>} label="Provider" value={meta.asOrganization|| (meta.asn?`AS${meta.asn}`:'Detecting…')}/><Detail icon={<Globe2/>} label="Public IP" value={meta.clientIp||'Detecting…'}/><Detail icon={<MapPin/>} label="Approx. location" value={[meta.city,meta.region||meta.country].filter(Boolean).join(', ')||'Detecting…'}/></div>{testedAt&&<div className="mt-5 flex items-center gap-2 border-t border-zinc-100 pt-4 text-xs text-zinc-400"><Clock3 className="h-3.5 w-3.5"/>Tested {testedAt.toLocaleString()}</div>}</div>
   </div>
   <div className="mx-auto mt-6 max-w-5xl rounded-2xl border border-zinc-200 bg-white px-5 py-5 sm:px-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
     <div><p className="text-sm font-bold text-zinc-950">Share your speed test</p><p className="mt-1 text-xs text-zinc-500">Share Runtime Speed Test or your latest result.</p></div>
     <div className="flex flex-wrap items-center gap-2">
      <ShareButton label="WhatsApp" onClick={()=>share('whatsapp')}><FaWhatsapp/></ShareButton>
      <ShareButton label="Facebook" onClick={()=>share('facebook')}><FaFacebookF/></ShareButton>
      <ShareButton label="X" onClick={()=>share('x')}><FaXTwitter/></ShareButton>
      <ShareButton label="LinkedIn" onClick={()=>share('linkedin')}><FaLinkedinIn/></ShareButton>
      <ShareButton label={copied?'Copied':'Copy link'} onClick={copyLink}><Copy/></ShareButton>
     </div>
    </div>
    <div className="mt-4 flex flex-col gap-3 border-t border-zinc-100 pt-4 sm:flex-row sm:items-center sm:justify-between">
     <div><p className="text-sm font-semibold text-zinc-900">Was this speed test useful?</p><p className="mt-0.5 text-xs text-zinc-500">{usefulCount>0?`${usefulCount} ${usefulCount===1?'person':'people'} found this useful.`:'Be the first to rate this tool.'}</p></div>
     <button type="button" onClick={markUseful} disabled={useful} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-full border px-5 text-sm font-bold transition ${useful?'border-[#3120ff]/20 bg-[#3120ff]/10 text-[#3120ff]':'border-zinc-200 bg-white text-zinc-800 hover:border-[#3120ff]/40 hover:text-[#3120ff]'}`}><ThumbsUp className="h-4 w-4"/>{useful?'Thanks!':'Yes, useful'}</button>
    </div>
   </div>
   <p className="mx-auto mt-4 max-w-3xl text-center text-[11px] leading-5 text-zinc-400">IP, provider and location are network-derived and may be approximate. The test transfers data to measure throughput. VPNs can change the network information shown.</p>
  </div></section>
  <section className="mx-auto max-w-4xl px-4 py-14 sm:px-6 sm:py-20"><div className="space-y-10 text-zinc-700"><Info title="What is an internet speed test?">An internet speed test measures how quickly data travels between your device and a test server. Runtime measures download and upload throughput, latency, jitter and packet loss to give you a broader picture of connection quality.</Info><div className="grid gap-8 sm:grid-cols-2"><Info title="Download vs upload speed">Download speed affects websites, video and files. Upload speed affects video calls, cloud backups and file uploads. Both are measured in megabits per second (Mbps).</Info><Info title="Unloaded vs loaded latency">Unloaded latency measures responsiveness when the connection is quiet. Loaded latency checks responsiveness after throughput activity. A large increase can indicate that the connection becomes less responsive when busy.</Info></div><div className="grid gap-8 sm:grid-cols-2"><Info title="What are jitter and packet loss?">Jitter is variation between latency measurements. Packet loss is the percentage of test requests that fail. Both can affect calls, gaming and other real-time applications.</Info><Info title="Why can results change?">Wi-Fi strength, other devices, ISP congestion, VPNs, browser activity and routing can affect a test. For comparison, run several tests under similar conditions.</Info></div><div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-6"><h2 className="text-xl font-bold text-zinc-950">Domains, DNS and the internet</h2><p className="mt-3 text-sm leading-7">Runtime provides domain registration and DNS management alongside practical internet tools. If a website is not loading as expected, connection speed is only one possibility—DNS configuration can also affect whether a domain reaches the correct service.</p><div className="mt-4 flex flex-wrap gap-3"><a href="/dns" className="text-sm font-bold text-[#3120ff] hover:underline">Learn about Runtime DNS</a><a href="/guides" className="text-sm font-bold text-[#3120ff] hover:underline">Read DNS guides</a></div></div></div></section>
 </div>;
};
const Result:React.FC<{icon:React.ReactNode;name:string;value:string;unit:string}>=({icon,name,value,unit})=><div><div className="flex items-center gap-2 text-zinc-500 [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:text-[#3120ff]"><span>{icon}</span><span className="text-[11px] font-semibold uppercase tracking-wide">{name}</span></div><div className="mt-1 flex items-end gap-1.5"><span className="text-2xl font-bold tabular-nums text-zinc-950 sm:text-3xl">{value}</span><span className="pb-1 text-[11px] text-zinc-400">{unit}</span></div></div>;
const ShareButton:React.FC<{label:string;onClick:()=>void;children:React.ReactNode}>=({label,onClick,children})=><button type="button" onClick={onClick} aria-label={label} title={label} className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-zinc-200 bg-white text-zinc-600 transition hover:border-[#3120ff]/40 hover:bg-[#3120ff]/5 hover:text-[#3120ff] [&_svg]:h-4 [&_svg]:w-4">{children}</button>;
const Detail:React.FC<{icon:React.ReactNode;label:string;value:string}>=({icon,label,value})=><div className="min-w-0"><div className="flex items-center gap-2 text-zinc-400 [&_svg]:h-3.5 [&_svg]:w-3.5"><span>{icon}</span><span className="text-[10px] font-bold uppercase tracking-wider">{label}</span></div><p className="mt-1 truncate text-sm font-semibold text-zinc-800" title={value}>{value}</p></div>;
const Info:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><div><h2 className="text-xl font-bold tracking-tight text-zinc-950">{title}</h2><p className="mt-3 text-sm leading-7">{children}</p></div>;
